version: '3.8'

services:

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/videodb
      - SECRET_KEY=your_secret_key_here
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_URL=minio:9000
      - MINIO_BUCKET=videos
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - minio
    networks:
      - app-network


  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videodb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

  # MinIO Storage
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_DOMAIN=localhost
      - MINIO_CORS_ALLOW_ALL=true
      - MINIO_BROWSER=on
      - MINIO_REGION=us-east-1
      - MINIO_API_CORS_ALLOW_ORIGIN=*
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client for setup
  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./backend/scripts:/scripts
    entrypoint: >
      /bin/sh -c "
      chmod +x /scripts/setup_minio.sh &&
      /scripts/setup_minio.sh
      "
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:

